
# ====== Service Configuration ====== #
TEST_MODE: True
ARTICLE_PARSER_LAMBDA: "test_sele"
MAX_LEN: 95
STOP_WORDS: ["카풀", "판매", "팝니다", "구매", "구입", "삽니다"]


# ====== AWS Auth Info ====== #
ACCESS_ID: "AKIAI5EEGQOAMNRFSHIQ"
ACCESS_KEY: "2wZnbjlU378XWYzpzKMcfrcceThRA8cXvqXKaw8j"
ROLE: "arn:aws:iam::915999582461:role/role_guin"
REGION_NAME: "ap-northeast-2"
BUCKET_NAME: "guin-bucket"


# ======= ARA Auth Info ====== #
ARA_ID: "whwodud98"
ARA_KEY: "rocketboy7!"

ARA_WANTED_BASE_URL: "https://ara.kaist.ac.kr/board/Wanted/{}"

DEBUG_MODE: False


# ====== Telegram Channel Info ====== #
TEST_BOT_TOKEN: "698252085:AAGSCCjQrcgCQFWiDU2p6q08mbDr3ia9NkM"
TEST_CHANNEL_URL: "@kaist9in_test"
TEST_ARA_WANTED_FILE_NAME: "ara_wanted_posts_test.csv"

DEPLOY_BOT_TOKEN: "592373269:AAFcgDyCX6aH-KixGW7jOUwauSq2UWzhjjk"
DEPLOY_CHANNEL_URL: "@kaist9in"
DEPLOY_ARA_WANTED_FILE_NAME: "ara_wanted_posts_deploy.csv"


